version: "2"
services:
  main:
    image: ndaidong/webserver
    volumes:
      - .:/home:z
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - NODE_ENV=production
    # restart: always
    entrypoint: |
      bash -c 'bash -s <<EOF
      npm install
      npm start
      EOF'
